[main_pod]
name = "wordpress-pod"
quadlet = """
[Unit]
After=network.target

[Pod]

[Install]
WantedBy=multi-user.target default.target
"""

[[replaceables]]
id = "a"
dev = "wordpress"
prod = "wordpress-prod"

[[quadlets]]
name = "wordpress-app"
type = "Container"
quadlet = """
[Container]
Label=app=wordpress
Pod=wordpress-pod
ContainerName=wordpress-app
Image=docker.io/library/wordpress:6
Network=<<<.a>>>
Volume=wordpress-app.volume:/var/www/html
Environment=WORDPRESS_DB_HOST=wordpress-db
Environment=WORDPRESS_DB_USER=wordpress
Environment=WORDPRESS_DB_NAME=wordpress
# This one should be stored in a secret
Environment=WORDPRESS_DB_PASSWORD=password
PublishPort=8080:80
"""

[[quadlets]]
name = "wordpress-db"
type = "Container"
quadlet = """
[Container]
Label=app=wordpress
Pod=wordpress-pod
ContainerName=wordpress-db
Image=docker.io/library/mariadb:10
Network=wordpress
Volume=wordpress-db.volume:/var/lib/mysql
Environment=MARIADB_RANDOM_ROOT_PASSWORD=1
Environment=MARIADB_USER=wordpress
Environment=MARIADB_DATABASE=wordpress
# This one should be stored in a secret
Environment=MARIADB_PASSWORD=password
"""

[[quadlets]]
name = "wordpress-db"
type = "Volume"
quadlet="""
[Volume]
Label=app=wordpress
VolumeName=wordpress-db.volume
"""
[[quadlets]]
name = "wordpress-app"
type = "Volume"
quadlet="""
[Volume]
Label=app=wordpress
VolumeName=wordpress-app.volume
"""

[[quadlets]]
name = "wordpress"
type = "Network"
quadlet="""
[Network]
Label=app=wordpress
NetworkName=wordpress
"""
