[main_pod]
name = "wordpress-pod"
quadlet = """
[Unit]
After=network.target

[Pod]

[Install]
WantedBy=multi-user.target default.target
"""

[[replaceables]]
id = "a"
dev = "wordpress"
prod = "wordpress-prod"

# WordPress FPM Container
[[quadlets]]
name = "wordpress-app"
type = "Container"
quadlet = """
[Container]
Label=app=wordpress
Pod=wordpress-pod
ContainerName=wordpress-app
Image=docker.io/library/wordpress:6
Network=wordpress.network
PublishPort=8080:80
Volume=wordpress-app.volume:/var/www/html
Environment=WORDPRESS_DB_HOST=wordpress-db
Environment=WORDPRESS_DB_USER=wordpress
Environment=WORDPRESS_DB_NAME=wordpress
Environment=WORDPRESS_DB_PASSWORD=password
"""

# MariaDB Container
[[quadlets]]
name = "wordpress-db"
type = "Container"
quadlet = """
[Container]
Label=app=wordpress
Pod=wordpress-pod
Image=docker.io/library/mariadb:10
ContainerName=wordpress-db
Network=wordpress.network
Volume=wordpress-db.volume:/var/lib/mysql
Environment=MARIADB_RANDOM_ROOT_PASSWORD=1
Environment=MARIADB_USER=wordpress
Environment=MARIADB_DATABASE=wordpress
Environment=MARIADB_PASSWORD=password
"""

# WordPress DB Volume
[[quadlets]]
name = "wordpress-db"
type = "Volume"
quadlet = """
[Volume]
"""

# WordPress App Volume
[[quadlets]]
name = "wordpress-app"
type = "Volume"
quadlet = """
[Volume]
"""

# WordPress Network
[[quadlets]]
name = "wordpress"
type = "Network"
quadlet = """
[Network]
"""
